### PR TITLE
gc.rs: `LIMIT` number of `orphan_chunks`, fixes #115

### LINKED ISSUE #115: Bug in `gc.rs` causing a `sqlx` panic that completely crashes `atticd`
Specifically, we're getting this panic from `atticd`:

```
thread 'main' panicked at 'assertion failed: self.param_types.len() <= (u16::MAX as usize)'
```

... which is related to this sqlx issue: https://github.com/launchbadge/sqlx/issues/671#issuecomment-687043510 but only because the number of chunks to garbage collect have grown beyond psql's purported bind parameter limit.

We narrowed the issue down (via the stack trace) to this query:

https://github.com/zhaofengli/attic/blob/6eabc3f02fae3683bffab483e614bebfcd476b21/server/src/gc.rs#L184

This problem takes down `atticd` entirely. We will submit a PR to fix this but I wanted to open this ticket for tracking purposes.

### PR DESCRIPTION
**Pull request by ixmatus**
This change fixes the immediate issue documented by #115.

There are some notable caveats though: for both mysql and sqlite, the parameter limits are configurable in the database, so my choice to use the defaults isn't adequate (but it is at least better than having no limit at all).

I think the more sensible and general approach that would solve both of these problems would be to:

- Limit `orphan_chunks` to something static and small, e.g 300 results.
- Use chained `OR`s instead of `IN` to get the most performant query possible.

... I didn't implement that though because we need something that brings attic back into service ASAP and I think that change is much more invasive than the one I'm proposing here and wanted to feel out @zhaofengli's receptiveness to that kind of change.

[EDIT] another more general approach would be to write a SELECT query for the orphan chunks that is used to get the chunks we need to delete from S3 and then reuse that query expression in the IN clause of the delete_many, then we wouldn't need any limit.

### CODE REVIEW

File: server/src/gc.rs [hunk 1]
```diff
@@ -158,6 +158,15 @@ async fn run_reap_orphan_chunks(state: &State) -> Result<()> {
     let db = state.database().await?;
     let storage = state.storage().await?;
 
+    let orphan_chunk_id_limit = match db.get_database_backend() {
+        // Default value of --max-allowed-packet https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet
+        sea_orm::DatabaseBackend::MySql    => 67108864,
```
Comment (baloo) [inline server/src/gc.rs:163]: `max_allowed_packet` sets the binary size of a message to and from mysql.
This is a different thing than the limit in the SQL sense. 
I would just limit that to a value of 1000 instead (I'm not aware of any variable setting the limit, beside the `max_allowed_packet` but this is the size after encoding).
```suggestion
        sea_orm::DatabaseBackend::MySql    => 1000,
```

Comment (ixmatus) [reply server/src/gc.rs:163]: I chose that value according to this stackoverflow answer: https://stackoverflow.com/questions/12666502/mysql-in-clause-max-number-of-arguments.

**Comment by ixmatus** [comment]
Testing indicates this is not the problem.

**Comment by ixmatus** [comment]
Reopening now that I've determined the correct location to limit the result set: [2705d1d](https://github.com/zhaofengli/attic/pull/116/commits/2705d1d90b153fb855307344bec4c48cb1e78c38).

File: server/src/gc.rs (hunk 1 above)
Comment (baloo) [reply server/src/gc.rs:163]: I think the stackoverflow answer says the same thing as what I'm saying.
The limit is a binary size limit, not a limit of arguments.

**Review by baloo — APPROVED** [review]
The postgres flow was deployed and tested. We did not test neither Mysql nor sqlite.

**Review by mweinelt — APPROVED** [review]
Tested with postgresql and resolves the crashing behavior.

**Comment by ixmatus** [comment]
@zhaofengli, can you review and merge this now that we have multiple verifications?

**Comment by zhaofengli** [comment]
Tested to work. This does mean some chunks will be stuck in the Deleted state until the next GC run, but it's a good compromise for the time being.
